# Configuration of checks run by pre-commit
#
# The tests are executed in the CI pipeline,
# see CONTRIBUTING.rst for further instructions.
# You can also run the checks directly at the terminal, e.g.
#
# $ pre-commit install
# $ pre-commit run --all-files
#
repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.238'
  hooks:
  - id: ruff
