name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.10' ]

    steps:
    - uses: actions/checkout@v4

    - name: Cache emodb
      uses: actions/cache@v4
      with:
        path: emodb-src
        key: emodb-ubuntu

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Ubuntu - install graphviz
      run: |
        sudo apt-get update
        sudo apt-get install --yes graphviz

    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install docs requirements
      run: pip install -r docs/requirements.txt

    - name: Test building documentation
      run: python -m sphinx docs/ docs/_build/ -b html -W

    - name: Check links in documentation
      run: python -m sphinx docs/ docs/_build/ -b linkcheck -W
